name: NodeJs publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js for GitHub Packages
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with your desired Node.js version
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Ibrokhim@1006'  # Replace with your GitHub username or organization

      - name: Install npm dependencies
        run: npm install

      - name: Publish to GitHub Packages
        run: npm publish --access public

      - name: Setup .npmrc for npm registry
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

      - name: Publish to npm registry
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
